---
- name: Add Virtualbox repository
  apt_key: 
    url: "{{ item }}"
    state: present
  loop:
    - "https://www.virtualbox.org/download/oracle_vbox.asc"
    - "https://www.virtualbox.org/download/oracle_vbox_2016.asc"

- name: Configure the VirtualBox APT repositories
  apt_repository: 
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present

- name: Install VirtualBox
  apt: 
    pkg: virtualbox-{{ virtualbox_version }}
    state: present
    update_cache: yes

- name: Download vagrant
  get_url: url={{ vagrant_url_rpm }} dest={{vagrant_tmp_rpm}}

- name: Install vagrant for RedHat OS family
  yum: name={{vagrant_tmp_rpm}}